// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk6qJsdyIGOxIdAGtHzwXvT2zNBLicxmM',
    appId: '1:381376260296:web:ee3a266d95c7f56d5f5dfd',
    messagingSenderId: '381376260296',
    projectId: 'scholar-chat-c20d8',
    authDomain: 'scholar-chat-c20d8.firebaseapp.com',
    storageBucket: 'scholar-chat-c20d8.appspot.com',
    measurementId: 'G-8NL8R4RD0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtA0J80AtbvAP89jb2qbyrB3cVR5vSV_M',
    appId: '1:381376260296:android:25bbeed2502d220a5f5dfd',
    messagingSenderId: '381376260296',
    projectId: 'scholar-chat-c20d8',
    storageBucket: 'scholar-chat-c20d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2XfzIOZlkJFuwR3J_zio2C7g6xY9AvIU',
    appId: '1:381376260296:ios:634c0265ae21b6a75f5dfd',
    messagingSenderId: '381376260296',
    projectId: 'scholar-chat-c20d8',
    storageBucket: 'scholar-chat-c20d8.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2XfzIOZlkJFuwR3J_zio2C7g6xY9AvIU',
    appId: '1:381376260296:ios:4a78bd924d73b9d45f5dfd',
    messagingSenderId: '381376260296',
    projectId: 'scholar-chat-c20d8',
    storageBucket: 'scholar-chat-c20d8.appspot.com',
    iosBundleId: 'com.example.scholarChat.RunnerTests',
  );
}
